version: 2.1
orbs:
  android: circleci/android@0.2.1
executors:
  android-executor:
    docker:
      - image: circleci/android:api-28-node
    working_directory: ~/purchases-android
    environment:
      JVM_OPTS: -Xmx3200m
      CIRCLE_JDK_VERSION: oraclejdk8

jobs:
  build:
    executor: android-executor
    steps:
      - checkout
      - android/accept-licenses
  test:
    executor: android-executor
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle.kts" }}-{{ checksum  "purchases/build.gradle" }}
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle.kts" }}-{{ checksum  "purchases/build.gradle" }}
      - android/restore-build-cache
      - run:
          name: Run Tests
          command: ./gradlew lint test
      - run:
          name: Test coverage report
          command: ./gradlew testDebugUnitTestCoverage coveralls
      - run:
          name: Detekt
          command: ./gradlew detektAll
      - android/save-build-cache
      - store_artifacts:
          path: purchases/build/reports
      - store_test_results:
          path: purchases/build/test-results

  danger:
    executor: android-executor
    steps:
      - checkout
      - run:
          name: Installing kotlin compiler 1.3.70
          command: |
            curl -o kotlin-compiler.zip -L https://github.com/JetBrains/kotlin/releases/download/v1.3.70/kotlin-compiler-1.3.70.zip
            unzip -d /usr/local/ kotlin-compiler.zip
            echo 'PATH=/usr/local/kotlinc/bin:$PATH' >> ~/.bash_profile
            rm -rf kotlin-compiler.zip
      - run:
          name: Installing gradle 5.6.2
          command: |
            curl -o gradle.zip -L https://downloads.gradle-dn.com/distributions/gradle-5.6.2-bin.zip
            sudo mkdir /opt/gradle
            sudo unzip -d /opt/gradle gradle.zip
            echo 'export PATH=/opt/gradle/gradle-5.6.2/bin:$PATH' >> ~/.bash_profile
            rm -rf gradle.zip
            source ~/.bash_profile
      - run:
          name: Install danger
          command: |
            sudo npm install -g danger
            git clone https://github.com/danger/kotlin.git --single-branch --depth 1 _danger-kotlin
            cd _danger-kotlin && make install
            cd ..
            rm -rf _danger-kotlin
      - run:
          name: Danger
          command: danger-kotlin ci

  docs-deploy:
    executor: android-executor
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle.kts" }}-{{ checksum  "purchases/build.gradle" }}
      - android/restore-build-cache
      - run:
          name: Install awscli
          command: sudo pip install awscli
      - run:
          name: Dokka
          command: ./gradlew dokka
      - run:
          name: Deploy to S3
          command: aws s3 sync ~/purchases-android/docs s3://purchases-docs/android --delete --acl public-read
      - run:
          name: Invalidate CloudFront caches
          command: aws cloudfront create-invalidation --distribution-id EPTW7F3CB566V --paths "/*"

  deploy:
    executor: android-executor
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle.kts" }}-{{ checksum  "purchases/build.gradle" }}
      - run:
          name: Deployment
          command: |
            .buildscripts/deploy_snapshot.sh

  assemble:
    executor: android-executor
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle.kts" }}-{{ checksum  "purchases/build.gradle" }}
      - android/restore-build-cache
      - run:
          name: Assemble
          command: ./gradlew assemble
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle.kts" }}-{{ checksum  "purchases/build.gradle" }}
      - android/save-build-cache

workflows:
  version: 2
  test-assemble-deploy-docs:
    jobs:
      - build
      - danger:
          requires:
            - build
      - test:
          requires:
            - build
      - assemble:
          requires:
            - build
      - deploy:
          requires:
            - assemble
          filters:
            branches:
              only: master
      - docs-deploy:
          filters:
            tags:
              only: /^(\d+\.)(\d+\.)(\d+)$/
            branches:
              ignore: /.*/